name: apz_animation
description: A new Flutter project to gif as overlay.
version: 1.0.0

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - packages/apz_animation/gif/failed.gif
    - packages/apz_animation/gif/success.gif

