name: apz_crypto
description: "Dart plugin which helps in Cryptography."
version: 1.0.0
homepage:

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0

dependencies:
  flutter:
    sdk: flutter
  pointycastle: ^4.0.0
  asn1lib: ^1.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
