name: apz_utils
description: A utility package for Appzillon-Neu Flutter projects
version: 1.0.0

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.0.2+1
  provider: ^6.1.1
  path_provider: ^2.1.2
  string_validator: ^1.1.0
  url_launcher: ^6.3.1
  flutter_cache_manager: 3.4.1
  js: 0.6.7
  web: 1.1.1
  apz_preference:
    git:
      url: http://prodgit.i-exceed.com:8009/appzillon-neu/core.git
      ref: develop
      path: apz_core/preference/v1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1
  flutter_lints: ^5.0.0
  custom_lint: ^0.7.0
  apz_custom_lint:
    git:
      url: http://prodgit.i-exceed.com:8009/appzillon-neu/core.git
      ref: develop
      path: apz_core/custom_lint/v1.0.0
